# Generated by Django 4.2.9 on 2024-05-29 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='cards.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='cards', through='cards.CardTag', to='cards.tag', verbose_name='Теги'),
        ),
        migrations.AlterUniqueTogether(
            name='cardtag',
            unique_together={('card', 'tag')},
        ),
    ]
